const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.NextPrevLayout
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{planoDeFundo: 0},
	{Sólido: 0},
	{chão: 0},
	{lago: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{nyanCat: 0},
	{arvore: 0},
	{Teclado: 0},
	{grama: 0},
	{sol: 0},
	{nuvem: 0},
	{BarreiraInvisivel: 0},
	{Áudio: 0},
	{peixe: 0},
	{PONTO: 0},
	{fotopeixe: 0},
	{quadro: 0},
	{flores1: 0},
	{flores2: 0},
	{caixa1: 0},
	{caixa2: 0},
	{caixa3: 0},
	{joelhocano: 0},
	{cano: 0},
	{plataforma: 0},
	{placa: 0},
	{portal: 0},
	{efeito: 0},
	{BarreiraEfeito: 0},
	{caixa4: 0},
	{final1: 0},
	{plateia: 0},
	{arquibancada: 0},
	{barreiraDeSom: 0},
	{planodefundoentrada: 0},
	{titulo: 0},
	{PLAY: 0},
	{Mouse: 0},
	{montanhas: 0},
	{céu: 0},
	{Esmaecer: 0},
	{teclas: 0},
	{Botão: 0},
	{JOGARNOVAMENTE: 0},
	{PROXIMO: 0},
	{efeito2: 0},
	{MENU: 0},
	{caverna: 0},
	{caverna2: 0},
	{fundoPreto: 0},
	{chão2: 0},
	{tocha: 0},
	{luz: 0},
	{SAIR: 0},
	{pedestal: 0},
	{estatua: 0},
	{barreiraevento: 0},
	{barreiralentidao: 0},
	{olhosFundo: 0},
	{PEDRAS: 0},
	{NIVEL: 0},
	{pedrinhas: 0},
	{final2: 0},
	{Navegador: 0},
	{fundoNiveis: 0},
	{Nivel1: 0},
	{Nivel2: 0},
	{barreiraSom: 0},
	{Sprite: 0},
	{PLAYAGAIN2: 0},
	{placa2: 0},
	{pontuação: 0},
	{ação: 0}
];

self.InstanceType = {
	planoDeFundo: class extends self.ITiledBackgroundInstance {},
	chão: class extends self.ISpriteInstance {},
	lago: class extends self.ISpriteInstance {},
	nyanCat: class extends self.ISpriteInstance {},
	arvore: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	grama: class extends self.ISpriteInstance {},
	sol: class extends self.ISpriteInstance {},
	nuvem: class extends self.ISpriteInstance {},
	BarreiraInvisivel: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	peixe: class extends self.ISpriteInstance {},
	PONTO: class extends self.ITextInstance {},
	fotopeixe: class extends self.ISpriteInstance {},
	quadro: class extends self.ISpriteInstance {},
	flores1: class extends self.ISpriteInstance {},
	flores2: class extends self.ISpriteInstance {},
	caixa1: class extends self.ISpriteInstance {},
	caixa2: class extends self.ISpriteInstance {},
	caixa3: class extends self.ISpriteInstance {},
	joelhocano: class extends self.ISpriteInstance {},
	cano: class extends self.ISpriteInstance {},
	plataforma: class extends self.ISpriteInstance {},
	placa: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	efeito: class extends self.ISpriteInstance {},
	BarreiraEfeito: class extends self.ISpriteInstance {},
	caixa4: class extends self.ISpriteInstance {},
	final1: class extends self.ISpriteInstance {},
	plateia: class extends self.ISpriteInstance {},
	arquibancada: class extends self.ISpriteInstance {},
	barreiraDeSom: class extends self.ISpriteInstance {},
	planodefundoentrada: class extends self.ITiledBackgroundInstance {},
	titulo: class extends self.ITextInstance {},
	PLAY: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	montanhas: class extends self.ITiledBackgroundInstance {},
	céu: class extends self.ISpriteInstance {},
	teclas: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	JOGARNOVAMENTE: class extends self.ITextInstance {},
	PROXIMO: class extends self.ITextInstance {},
	efeito2: class extends self.ISpriteInstance {},
	MENU: class extends self.ITextInstance {},
	caverna: class extends self.ISpriteInstance {},
	caverna2: class extends self.ISpriteInstance {},
	fundoPreto: class extends self.ISpriteInstance {},
	chão2: class extends self.ISpriteInstance {},
	tocha: class extends self.ISpriteInstance {},
	luz: class extends self.ISpriteInstance {},
	SAIR: class extends self.ITextInstance {},
	pedestal: class extends self.ISpriteInstance {},
	estatua: class extends self.ISpriteInstance {},
	barreiraevento: class extends self.ISpriteInstance {},
	barreiralentidao: class extends self.ISpriteInstance {},
	olhosFundo: class extends self.ISpriteInstance {},
	PEDRAS: class extends self.ISpriteInstance {},
	NIVEL: class extends self.ITextInstance {},
	pedrinhas: class extends self.ISpriteInstance {},
	final2: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	fundoNiveis: class extends self.ISpriteInstance {},
	Nivel1: class extends self.ITextInstance {},
	Nivel2: class extends self.ITextInstance {},
	barreiraSom: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	PLAYAGAIN2: class extends self.ITextInstance {},
	placa2: class extends self.ISpriteInstance {}
}